name: hardware_buttons
description: A Flutter plugin for iOS and Android for detecting various hardware buttons such as volume and home button.
version: 1.0.1
authors:
  - TaeHeun Lee <nixstory@gmail.com>
  
homepage: https://github.com/reactspring/flutter_hardware_buttons

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.moum.hardware_buttons
    pluginClass: HardwareButtonsPlugin
